<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "grid_for_gridelements"
 *
 * Auto generated by Extension Builder 2019-04-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Multi Framework grids for GridElements',
    'description' => 'Add an easy to use grid element with GridElements. It\'s Framework independent. Prepared for Bootstrap v4.',
    'category' => 'plugin',
    'author' => 'Marco Schmidt',
    'author_email' => 'typo@schmidt-webmedia.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
            'gridelements' => '10.0.0-10.99.99'
        ],
        'conflicts' => [],
        'suggests' => [
            'frontend_editing' => ''
        ],
    ],
    'autoload' => [
        'psr-4' => ['SchmidtWebmedia\\GridForGridElements\\' => 'Classes']
    ],
];
